title: Michael Therapy
description: A grounded, straightforward space to talk things through.

url: "https://alexwatson1212.github.io"
baseurl: "/michaeldoe"

markdown: kramdown

plugins:
  - jekyll-seo-tag